# CONFIGURATION FILE FOR AGE-OF-ACQUISITION PREDICTION 
# TRAINING

# RANDOM SEED
seed: 2023

# DATA LOADING
aoapred_train_filepath: "data/aoapred-train.json"
aoapred_val_filepath: "data/aoapred-val.json"
# the test file is not used here but shall be included to check data subsets completeness
aoapred_test_filepath: "data/aoapred-test.json"

# MODEL TRAINING
train_loader:
  batch_size: 256
  num_workers: 4
  shuffle: True
val_loader:
  batch_size: 256
  num_workers: 4

# MODEL CONFIGS
tokenizer_name: bert-base-uncased
model_configs:
  model_name: bert-base-uncased
  interim_linear_dim: 1024


# TRAINER CLASS CONFIGS
trainer_configs:
  optimizer:
    lr: 5.0e-5
    weight_decay: 0.05
  scaler: true
  scheduler:
    use: True
    configs:
      mode: "min"
      factor: 0.5
      patience: 5
      min_lr: 6.0e-5
  wandb:
    use: false
    init_configs:
      entity: 
      reinit: true
      project: 
  max_saved_ckpts: 3


# EXPERIMENT CONFIGS
exp_configs:
  folder: exp/
  epoch: 2
  finetune:
    use: false
    ckpt: 
  