# CONFIGURATION FILE FOR AGE-OF-ACQUISITION PREDICTION 
# TRAINING

# RANDOM SEED
seed: 2023

# DATA LOADING
# the original csv file is not always used; only called when splitting is needec
aoa_csv_filepath: "data/aoa-data-chr.csv"
aoapred_train_filepath: "data/aoapred-train-chr.json"
aoapred_val_filepath: "data/aoapred-val-chr.json"
# the test file is not used here but shall be included to check data subsets completeness
aoapred_test_filepath: "data/aoapred-test.json"

# MODEL TRAINING
train_loader:
  batch_size: 512
  num_workers: 4
  shuffle: true
val_loader:
  batch_size: 512
  num_workers: 4

# MODEL CONFIGS
tokenizer_name: bert-base-uncased
model:
  # choices: "pretrained-emb", "early-fused", "later-fused"
  choice: pretrained-emb
  configs:
    # # EasyReg or DualReg
    # model_name: bert-base-uncased
    # lstm_hidden_dim: 512
    # lstm_num_layers: 2
    # interim_linear_dim: 512
    # dropout: 0.3
    # concat_wlen: true
    # concat_nsyl: true

    # PTEmbReg
    emb_dim: 256
    emb_dropout: 0.2
    interim_linear_dim: 2048
    lstm_hidden_dim: 1024
    lstm_num_layers: 3
    lstm_bidirectional: true
    lstm_dropout: 0.2
    use_lockedlstm: true
    concat_wlen: true
    concat_nsyl: false
  chridx_filepath: data/chr2idx.txt


# TRAINER CLASS CONFIGS
trainer_configs:
  optimizer:
    lr: 0.001
    weight_decay: 0.10
    amsgrad: true
    betas:
      - 0.9
      - 0.95
  scaler: true
  scheduler:
    use: true
    configs:
      mode: "min"
      factor: 0.5
      patience: 5
      min_lr: 1.0e-7
  max_saved_ckpts: 3


# EXPERIMENT CONFIGS
exp_configs:
  folder: exp/chr-pt
  anno: ""
  epoch: 20
  finetune:
    use: false
    ckpt: 
  wandb:
    use: false
    init_configs:
      name: 
      entity: 
      reinit: true
      project: 