# CONFIGURATION FILE FOR AGE-OF-ACQUISITION PREDICTION 
# TRAINING

# RANDOM SEED
seed: 2023

# DATA LOADING
# the original csv file is not always used; only called when splitting is needec
aoa_csv_filepath: "data/aoa-data.csv"
aoapred_train_filepath: "data/aoapred-train.json"
aoapred_val_filepath: "data/aoapred-val.json"
# the test file is not used here but shall be included to check data subsets completeness
aoapred_test_filepath: "data/aoapred-test.json"

# MODEL TRAINING
train_loader:
  batch_size: 256
  num_workers: 4
  shuffle: true
val_loader:
  batch_size: 256
  num_workers: 4

# MODEL CONFIGS
tokenizer_name: bert-base-uncased
model:
  choice: later-fused
  configs:
    model_name: bert-base-uncased
    interim_linear_dim: 32
    dropout: 0.5
    concat_wlen: true
    concat_nsyl: true


# TRAINER CLASS CONFIGS
trainer_configs:
  optimizer:
    lr: 5.0e-4
    weight_decay: 0.10
  scaler: true
  scheduler:
    use: true
    configs:
      mode: "min"
      factor: 0.5
      patience: 5
      min_lr: 5.0e-8
  wandb:
    use: true
    init_configs:
      name: 
      entity: Astromsoc
      reinit: true
      project: aoapred
  max_saved_ckpts: 2


# EXPERIMENT CONFIGS
exp_configs:
  folder: exp/test
  anno: ""
  epoch: 20
  finetune:
    use: false
    ckpt: 
  